package tftpclient.View;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileSystemView;
import tftpclient.Observers.TFTPObserver;
import tftpclient.TFTPReceive;
import tftpclient.TFTPSend;
import tftpclient.TFTPTransaction;

/**
 *
 * @author Antoine
 */
public class FrSend extends javax.swing.JPanel implements ActionListener, TFTPObserver {

    /**
     * Creates new form FrSend
     */
    public FrSend() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldIP = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButtonQuitter = new javax.swing.JButton();
        FileSystemView vueSysteme = FileSystemView.getFileSystemView();
        //récupération des répertoires
        File defaut = vueSysteme.getDefaultDirectory();
        jFileChooser = new javax.swing.JFileChooser(defaut);
        jLabel2 = new javax.swing.JLabel();
        jButtonEnvoyer = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();

        jTextFieldIP.setToolTipText("Adresse IP de destination");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(0, 204, 0));
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel1.setText("Adresse IP");

        jButtonQuitter.setText("Quitter");
        jButtonQuitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonQuitterMouseClicked(evt);
            }
        });

        jFileChooser.setCurrentDirectory(new java.io.File("C:\\Program Files\\NetBeans 8.0\\System.getProperty(\"user.dir\" )"));

        jLabel2.setText("Choix du fichier");

        jButtonEnvoyer.setText("Envoyer");
        jButtonEnvoyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnvoyerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 404, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jButtonEnvoyer)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonQuitter, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldIP, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jButtonEnvoyer)
                            .addComponent(jButtonQuitter))
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEnvoyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnvoyerActionPerformed
        if (jTextFieldIP.getText().length() != 0) {
            if (jFileChooser.getSelectedFile() != null) {
                TFTPSend send=new TFTPSend(jFileChooser.getSelectedFile(),jTextFieldIP.getText());
                send.addObserver(this);
                Thread monThread=new Thread(send);
                monThread.start();
            } else {
                jTextArea1.append("Pas de fichier sélectionné \n");
            }
        } else {
            jTextArea1.append("Pas d'ip saisie\n");
        }
    }//GEN-LAST:event_jButtonEnvoyerActionPerformed

    private void jButtonQuitterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonQuitterMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jButtonQuitterMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnvoyer;
    private javax.swing.JButton jButtonQuitter;
    private javax.swing.JFileChooser jFileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldIP;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void onErrorOccured(final String errormsg) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                jTextArea1.append(errormsg + "\n");
            }
        });
    }


    @Override
    public void onInfoSending(final String infoMsg) {
           SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                jTextArea1.append(infoMsg + "\n");
            }
        });
    }

    @Override
    public void onSendingEnd(char valeur) {
       SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                jTextArea1.append("Transfers Terminé avec succès" + "\n");
                jProgressBar1.setValue(0);
            }
        });
    }

    @Override
    public void onReceivingEnd(char valeur) {
        
    }

    @Override
    public void onProcessingSend(final int value) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                jProgressBar1.setValue(value);
            }
        });
    }
}
